// <auto-generated>
// Windows Forms designer layout. Edit using MainForm.cs > View Designer.
// </auto-generated>
#nullable disable

using System.Drawing;
using System.Windows.Forms;
using System.Xml.Linq;
using static System.Net.Mime.MediaTypeNames;
using Font = System.Drawing.Font;

namespace ChargeEm
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;

        // Standard component cleanup; no assignment logic.
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            RootLayout = new TableLayoutPanel();
            HeaderPanel = new Panel();
            CompanyNameLabel = new Label();
            CompanySubtitleLabel = new Label();
            PageTitleLabel = new Label();
            BodyPanel = new Panel();
            ContentLayout = new TableLayoutPanel();
            InputLayout = new TableLayoutPanel();
            CustomerPanel = new Panel();
            CustomerSectionLabel = new Label();
            CustomerHintLabel = new Label();
            NameLayout = new TableLayoutPanel();
            FirstNameCaptionLabel = new Label();
            FirstNameTextBox = new TextBox();
            MiddleInitialCaptionLabel = new Label();
            MiddleInitialTextBox = new TextBox();
            LastNameCaptionLabel = new Label();
            LastNameTextBox = new TextBox();
            MeasurementsLayout = new TableLayoutPanel();
            AgeCaptionLabel = new Label();
            AgeTextBox = new TextBox();
            HeightCaptionLabel = new Label();
            HeightTextBox = new TextBox();
            WeightCaptionLabel = new Label();
            WeightTextBox = new TextBox();
            CoveragePanel = new Panel();
            CoverageSectionLabel = new Label();
            CoverageInputCaptionLabel = new Label();
            CoverageAmountTextBox = new TextBox();
            DiscountOptionsPanel = new Panel();
            NoDiscountRadioButton = new RadioButton();
            PercentageDiscountRadioButton = new RadioButton();
            FlatDiscountRadioButton = new RadioButton();
            DiscountAmountsLayout = new TableLayoutPanel();
            PercentageDiscountCaptionLabel = new Label();
            PercentageDiscountTextBox = new TextBox();
            FlatDiscountCaptionLabel = new Label();
            FlatDiscountTextBox = new TextBox();
            DiscountHintLabel = new Label();
            ValidationPanel = new Panel();
            ValidationHeadingLabel = new Label();
            ValidationMessageLabel = new Label();
            QuotePanel = new Panel();
            QuoteSectionLabel = new Label();
            PreparedForCaptionLabel = new Label();
            CustomerNameLabel = new Label();
            QuotedCoverageLayout = new TableLayoutPanel();
            QuotedCoverageCaptionLabel = new Label();
            CoverageAmountLabel = new Label();
            RiskLayout = new TableLayoutPanel();
            RiskFactorCaptionLabel = new Label();
            RiskCategoryCaptionLabel = new Label();
            RiskFactorLabel = new Label();
            RiskCategoryLabel = new Label();
            QuoteAmountsLayout = new TableLayoutPanel();
            CostPerThousandCaptionLabel = new Label();
            CostPerThousandLabel = new Label();
            AnnualPremiumCaptionLabel = new Label();
            AnnualPremiumLabel = new Label();
            DiscountAmountCaptionLabel = new Label();
            DiscountAmountLabel = new Label();
            SubtotalCaptionLabel = new Label();
            SubtotalLabel = new Label();
            SalesTaxCaptionLabel = new Label();
            SalesTaxLabel = new Label();
            TotalPanel = new Panel();
            TotalCaptionLabel = new Label();
            TotalAnnualPremiumLabel = new Label();
            TotalHintLabel = new Label();
            QuoteStatusLabel = new Label();
            FooterPanel = new Panel();
            FooterDivider = new Panel();
            FooterHintLabel = new Label();
            ClearButton = new Button();
            GenerateQuoteButton = new Button();
            InputErrorProvider = new ErrorProvider(components);
            RootLayout.SuspendLayout();
            HeaderPanel.SuspendLayout();
            BodyPanel.SuspendLayout();
            ContentLayout.SuspendLayout();
            InputLayout.SuspendLayout();
            CustomerPanel.SuspendLayout();
            NameLayout.SuspendLayout();
            MeasurementsLayout.SuspendLayout();
            CoveragePanel.SuspendLayout();
            DiscountOptionsPanel.SuspendLayout();
            DiscountAmountsLayout.SuspendLayout();
            ValidationPanel.SuspendLayout();
            QuotePanel.SuspendLayout();
            QuotedCoverageLayout.SuspendLayout();
            RiskLayout.SuspendLayout();
            QuoteAmountsLayout.SuspendLayout();
            TotalPanel.SuspendLayout();
            FooterPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)InputErrorProvider).BeginInit();
            SuspendLayout();
            // 
            // RootLayout
            // 
            RootLayout.ColumnCount = 1;
            RootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            RootLayout.Controls.Add(HeaderPanel, 0, 0);
            RootLayout.Controls.Add(BodyPanel, 0, 1);
            RootLayout.Controls.Add(FooterPanel, 0, 2);
            RootLayout.Dock = DockStyle.Fill;
            RootLayout.Location = new Point(0, 0);
            RootLayout.Margin = new Padding(0);
            RootLayout.Name = "RootLayout";
            RootLayout.RowCount = 3;
            RootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 82F));
            RootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            RootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 74F));
            RootLayout.Size = new Size(1120, 800);
            RootLayout.TabIndex = 0;
            // 
            // HeaderPanel
            // 
            HeaderPanel.BackColor = Color.FromArgb(23, 45, 68);
            HeaderPanel.Controls.Add(CompanyNameLabel);
            HeaderPanel.Controls.Add(CompanySubtitleLabel);
            HeaderPanel.Controls.Add(PageTitleLabel);
            HeaderPanel.Dock = DockStyle.Fill;
            HeaderPanel.Location = new Point(0, 0);
            HeaderPanel.Margin = new Padding(0);
            HeaderPanel.Name = "HeaderPanel";
            HeaderPanel.Size = new Size(1120, 82);
            HeaderPanel.TabIndex = 0;
            // 
            // CompanyNameLabel
            // 
            CompanyNameLabel.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
            CompanyNameLabel.ForeColor = Color.White;
            CompanyNameLabel.Location = new Point(24, 9);
            CompanyNameLabel.Name = "CompanyNameLabel";
            CompanyNameLabel.Size = new Size(360, 38);
            CompanyNameLabel.TabIndex = 0;
            CompanyNameLabel.Text = "ChargEm";
            CompanyNameLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // CompanySubtitleLabel
            // 
            CompanySubtitleLabel.Font = new Font("Segoe UI", 9F);
            CompanySubtitleLabel.ForeColor = Color.FromArgb(214, 228, 240);
            CompanySubtitleLabel.Location = new Point(27, 48);
            CompanySubtitleLabel.Name = "CompanySubtitleLabel";
            CompanySubtitleLabel.Size = new Size(360, 20);
            CompanySubtitleLabel.TabIndex = 1;
            CompanySubtitleLabel.Text = "Life Insurance Company";
            CompanySubtitleLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // PageTitleLabel
            // 
            PageTitleLabel.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            PageTitleLabel.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            PageTitleLabel.ForeColor = Color.FromArgb(214, 228, 240);
            PageTitleLabel.Location = new Point(770, 26);
            PageTitleLabel.Name = "PageTitleLabel";
            PageTitleLabel.Size = new Size(326, 26);
            PageTitleLabel.TabIndex = 2;
            PageTitleLabel.Text = "Annual policy quotation";
            PageTitleLabel.TextAlign = ContentAlignment.MiddleRight;
            // 
            // BodyPanel
            // 
            BodyPanel.AutoScroll = true;
            BodyPanel.AutoScrollMinSize = new Size(1032, 636);
            BodyPanel.BackColor = Color.FromArgb(243, 245, 248);
            BodyPanel.Controls.Add(ContentLayout);
            BodyPanel.Dock = DockStyle.Fill;
            BodyPanel.Location = new Point(0, 82);
            BodyPanel.Margin = new Padding(0);
            BodyPanel.Name = "BodyPanel";
            BodyPanel.Padding = new Padding(0, 0, 0, 20);
            BodyPanel.Size = new Size(1120, 644);
            BodyPanel.TabIndex = 1;
            // 
            // ContentLayout
            // 
            ContentLayout.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            ContentLayout.ColumnCount = 3;
            ContentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 54F));
            ContentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 20F));
            ContentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 46F));
            ContentLayout.Controls.Add(InputLayout, 0, 0);
            ContentLayout.Controls.Add(QuotePanel, 2, 0);
            ContentLayout.Location = new Point(24, 20);
            ContentLayout.Margin = new Padding(0);
            ContentLayout.MinimumSize = new Size(984, 596);
            ContentLayout.Name = "ContentLayout";
            ContentLayout.RowCount = 1;
            ContentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            ContentLayout.Size = new Size(1072, 596);
            ContentLayout.TabIndex = 0;
            // 
            // InputLayout
            // 
            InputLayout.ColumnCount = 1;
            InputLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            InputLayout.Controls.Add(CustomerPanel, 0, 0);
            InputLayout.Controls.Add(CoveragePanel, 0, 1);
            InputLayout.Controls.Add(ValidationPanel, 0, 2);
            InputLayout.Dock = DockStyle.Fill;
            InputLayout.Location = new Point(0, 0);
            InputLayout.Margin = new Padding(0);
            InputLayout.Name = "InputLayout";
            InputLayout.RowCount = 3;
            InputLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 244F));
            InputLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 268F));
            InputLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            InputLayout.Size = new Size(568, 596);
            InputLayout.TabIndex = 0;
            // 
            // CustomerPanel
            // 
            CustomerPanel.BackColor = Color.White;
            CustomerPanel.BorderStyle = BorderStyle.FixedSingle;
            CustomerPanel.Controls.Add(CustomerSectionLabel);
            CustomerPanel.Controls.Add(CustomerHintLabel);
            CustomerPanel.Controls.Add(NameLayout);
            CustomerPanel.Controls.Add(MeasurementsLayout);
            CustomerPanel.Dock = DockStyle.Fill;
            CustomerPanel.Location = new Point(0, 0);
            CustomerPanel.Margin = new Padding(0, 0, 0, 16);
            CustomerPanel.Name = "CustomerPanel";
            CustomerPanel.Size = new Size(568, 228);
            CustomerPanel.TabIndex = 0;
            // 
            // CustomerSectionLabel
            // 
            CustomerSectionLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            CustomerSectionLabel.Font = new Font("Segoe UI", 15F, FontStyle.Bold);
            CustomerSectionLabel.ForeColor = Color.FromArgb(23, 45, 68);
            CustomerSectionLabel.Location = new Point(22, 16);
            CustomerSectionLabel.Name = "CustomerSectionLabel";
            CustomerSectionLabel.Size = new Size(522, 28);
            CustomerSectionLabel.TabIndex = 0;
            CustomerSectionLabel.Text = "Customer information";
            CustomerSectionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // CustomerHintLabel
            // 
            CustomerHintLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            CustomerHintLabel.Font = new Font("Segoe UI", 9F);
            CustomerHintLabel.ForeColor = Color.FromArgb(88, 106, 126);
            CustomerHintLabel.Location = new Point(22, 48);
            CustomerHintLabel.Name = "CustomerHintLabel";
            CustomerHintLabel.Size = new Size(522, 20);
            CustomerHintLabel.TabIndex = 1;
            CustomerHintLabel.Text = "Enter the customer's name and personal details.";
            CustomerHintLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // NameLayout
            // 
            NameLayout.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            NameLayout.ColumnCount = 3;
            NameLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            NameLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 90F));
            NameLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            NameLayout.Controls.Add(FirstNameCaptionLabel, 0, 0);
            NameLayout.Controls.Add(FirstNameTextBox, 0, 1);
            NameLayout.Controls.Add(MiddleInitialCaptionLabel, 1, 0);
            NameLayout.Controls.Add(MiddleInitialTextBox, 1, 1);
            NameLayout.Controls.Add(LastNameCaptionLabel, 2, 0);
            NameLayout.Controls.Add(LastNameTextBox, 2, 1);
            NameLayout.Location = new Point(22, 83);
            NameLayout.Margin = new Padding(0);
            NameLayout.Name = "NameLayout";
            NameLayout.RowCount = 2;
            NameLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 22F));
            NameLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            NameLayout.Size = new Size(522, 56);
            NameLayout.TabIndex = 0;
            // 
            // FirstNameCaptionLabel
            // 
            FirstNameCaptionLabel.Dock = DockStyle.Fill;
            FirstNameCaptionLabel.Font = new Font("Segoe UI", 9F);
            FirstNameCaptionLabel.ForeColor = Color.FromArgb(23, 45, 68);
            FirstNameCaptionLabel.Location = new Point(0, 0);
            FirstNameCaptionLabel.Margin = new Padding(0);
            FirstNameCaptionLabel.Name = "FirstNameCaptionLabel";
            FirstNameCaptionLabel.Size = new Size(216, 22);
            FirstNameCaptionLabel.TabIndex = 0;
            FirstNameCaptionLabel.Text = "First name";
            FirstNameCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // FirstNameTextBox
            // 
            FirstNameTextBox.AccessibleName = "First name";
            FirstNameTextBox.BorderStyle = BorderStyle.FixedSingle;
            FirstNameTextBox.Dock = DockStyle.Top;
            FirstNameTextBox.Font = new Font("Segoe UI", 10F);
            FirstNameTextBox.Location = new Point(0, 24);
            FirstNameTextBox.Margin = new Padding(0, 2, 10, 0);
            FirstNameTextBox.Name = "FirstNameTextBox";
            FirstNameTextBox.PlaceholderText = "First name";
            FirstNameTextBox.Size = new Size(206, 25);
            FirstNameTextBox.TabIndex = 0;
            // 
            // MiddleInitialCaptionLabel
            // 
            MiddleInitialCaptionLabel.Dock = DockStyle.Fill;
            MiddleInitialCaptionLabel.Font = new Font("Segoe UI", 9F);
            MiddleInitialCaptionLabel.ForeColor = Color.FromArgb(23, 45, 68);
            MiddleInitialCaptionLabel.Location = new Point(216, 0);
            MiddleInitialCaptionLabel.Margin = new Padding(0);
            MiddleInitialCaptionLabel.Name = "MiddleInitialCaptionLabel";
            MiddleInitialCaptionLabel.Size = new Size(90, 22);
            MiddleInitialCaptionLabel.TabIndex = 1;
            MiddleInitialCaptionLabel.Text = "Middle initial";
            MiddleInitialCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // MiddleInitialTextBox
            // 
            MiddleInitialTextBox.AccessibleName = "Middle initial";
            MiddleInitialTextBox.BorderStyle = BorderStyle.FixedSingle;
            MiddleInitialTextBox.Dock = DockStyle.Top;
            MiddleInitialTextBox.Font = new Font("Segoe UI", 10F);
            MiddleInitialTextBox.Location = new Point(216, 24);
            MiddleInitialTextBox.Margin = new Padding(0, 2, 10, 0);
            MiddleInitialTextBox.MaxLength = 1;
            MiddleInitialTextBox.Name = "MiddleInitialTextBox";
            MiddleInitialTextBox.PlaceholderText = "M";
            MiddleInitialTextBox.Size = new Size(80, 25);
            MiddleInitialTextBox.TabIndex = 1;
            // 
            // LastNameCaptionLabel
            // 
            LastNameCaptionLabel.Dock = DockStyle.Fill;
            LastNameCaptionLabel.Font = new Font("Segoe UI", 9F);
            LastNameCaptionLabel.ForeColor = Color.FromArgb(23, 45, 68);
            LastNameCaptionLabel.Location = new Point(306, 0);
            LastNameCaptionLabel.Margin = new Padding(0);
            LastNameCaptionLabel.Name = "LastNameCaptionLabel";
            LastNameCaptionLabel.Size = new Size(216, 22);
            LastNameCaptionLabel.TabIndex = 2;
            LastNameCaptionLabel.Text = "Last name";
            LastNameCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // LastNameTextBox
            // 
            LastNameTextBox.AccessibleName = "Last name";
            LastNameTextBox.BorderStyle = BorderStyle.FixedSingle;
            LastNameTextBox.Dock = DockStyle.Top;
            LastNameTextBox.Font = new Font("Segoe UI", 10F);
            LastNameTextBox.Location = new Point(306, 24);
            LastNameTextBox.Margin = new Padding(0, 2, 0, 0);
            LastNameTextBox.Name = "LastNameTextBox";
            LastNameTextBox.PlaceholderText = "Last name";
            LastNameTextBox.Size = new Size(216, 25);
            LastNameTextBox.TabIndex = 2;
            // 
            // MeasurementsLayout
            // 
            MeasurementsLayout.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            MeasurementsLayout.ColumnCount = 3;
            MeasurementsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
            MeasurementsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
            MeasurementsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
            MeasurementsLayout.Controls.Add(AgeCaptionLabel, 0, 0);
            MeasurementsLayout.Controls.Add(AgeTextBox, 0, 1);
            MeasurementsLayout.Controls.Add(HeightCaptionLabel, 1, 0);
            MeasurementsLayout.Controls.Add(HeightTextBox, 1, 1);
            MeasurementsLayout.Controls.Add(WeightCaptionLabel, 2, 0);
            MeasurementsLayout.Controls.Add(WeightTextBox, 2, 1);
            MeasurementsLayout.Location = new Point(22, 153);
            MeasurementsLayout.Margin = new Padding(0);
            MeasurementsLayout.Name = "MeasurementsLayout";
            MeasurementsLayout.RowCount = 2;
            MeasurementsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 22F));
            MeasurementsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            MeasurementsLayout.Size = new Size(522, 56);
            MeasurementsLayout.TabIndex = 1;
            // 
            // AgeCaptionLabel
            // 
            AgeCaptionLabel.Dock = DockStyle.Fill;
            AgeCaptionLabel.Font = new Font("Segoe UI", 9F);
            AgeCaptionLabel.ForeColor = Color.FromArgb(23, 45, 68);
            AgeCaptionLabel.Location = new Point(0, 0);
            AgeCaptionLabel.Margin = new Padding(0);
            AgeCaptionLabel.Name = "AgeCaptionLabel";
            AgeCaptionLabel.Size = new Size(174, 22);
            AgeCaptionLabel.TabIndex = 0;
            AgeCaptionLabel.Text = "Age (years)";
            AgeCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // AgeTextBox
            // 
            AgeTextBox.AccessibleName = "Age (years)";
            AgeTextBox.BorderStyle = BorderStyle.FixedSingle;
            AgeTextBox.Dock = DockStyle.Top;
            AgeTextBox.Font = new Font("Segoe UI", 10F);
            AgeTextBox.Location = new Point(0, 24);
            AgeTextBox.Margin = new Padding(0, 2, 10, 0);
            AgeTextBox.Name = "AgeTextBox";
            AgeTextBox.PlaceholderText = "Years";
            AgeTextBox.Size = new Size(164, 25);
            AgeTextBox.TabIndex = 0;
            // 
            // HeightCaptionLabel
            // 
            HeightCaptionLabel.Dock = DockStyle.Fill;
            HeightCaptionLabel.Font = new Font("Segoe UI", 9F);
            HeightCaptionLabel.ForeColor = Color.FromArgb(23, 45, 68);
            HeightCaptionLabel.Location = new Point(174, 0);
            HeightCaptionLabel.Margin = new Padding(0);
            HeightCaptionLabel.Name = "HeightCaptionLabel";
            HeightCaptionLabel.Size = new Size(174, 22);
            HeightCaptionLabel.TabIndex = 1;
            HeightCaptionLabel.Text = "Height (inches)";
            HeightCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // HeightTextBox
            // 
            HeightTextBox.AccessibleName = "Height (inches)";
            HeightTextBox.BorderStyle = BorderStyle.FixedSingle;
            HeightTextBox.Dock = DockStyle.Top;
            HeightTextBox.Font = new Font("Segoe UI", 10F);
            HeightTextBox.Location = new Point(174, 24);
            HeightTextBox.Margin = new Padding(0, 2, 10, 0);
            HeightTextBox.Name = "HeightTextBox";
            HeightTextBox.PlaceholderText = "Inches";
            HeightTextBox.Size = new Size(164, 25);
            HeightTextBox.TabIndex = 1;
            // 
            // WeightCaptionLabel
            // 
            WeightCaptionLabel.Dock = DockStyle.Fill;
            WeightCaptionLabel.Font = new Font("Segoe UI", 9F);
            WeightCaptionLabel.ForeColor = Color.FromArgb(23, 45, 68);
            WeightCaptionLabel.Location = new Point(348, 0);
            WeightCaptionLabel.Margin = new Padding(0);
            WeightCaptionLabel.Name = "WeightCaptionLabel";
            WeightCaptionLabel.Size = new Size(174, 22);
            WeightCaptionLabel.TabIndex = 2;
            WeightCaptionLabel.Text = "Weight (pounds)";
            WeightCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // WeightTextBox
            // 
            WeightTextBox.AccessibleName = "Weight (pounds)";
            WeightTextBox.BorderStyle = BorderStyle.FixedSingle;
            WeightTextBox.Dock = DockStyle.Top;
            WeightTextBox.Font = new Font("Segoe UI", 10F);
            WeightTextBox.Location = new Point(348, 24);
            WeightTextBox.Margin = new Padding(0, 2, 0, 0);
            WeightTextBox.Name = "WeightTextBox";
            WeightTextBox.PlaceholderText = "Pounds";
            WeightTextBox.Size = new Size(174, 25);
            WeightTextBox.TabIndex = 2;
            // 
            // CoveragePanel
            // 
            CoveragePanel.BackColor = Color.White;
            CoveragePanel.BorderStyle = BorderStyle.FixedSingle;
            CoveragePanel.Controls.Add(CoverageSectionLabel);
            CoveragePanel.Controls.Add(CoverageInputCaptionLabel);
            CoveragePanel.Controls.Add(CoverageAmountTextBox);
            CoveragePanel.Controls.Add(DiscountOptionsPanel);
            CoveragePanel.Controls.Add(DiscountAmountsLayout);
            CoveragePanel.Controls.Add(DiscountHintLabel);
            CoveragePanel.Dock = DockStyle.Fill;
            CoveragePanel.Location = new Point(0, 244);
            CoveragePanel.Margin = new Padding(0, 0, 0, 14);
            CoveragePanel.Name = "CoveragePanel";
            CoveragePanel.Size = new Size(568, 254);
            CoveragePanel.TabIndex = 1;
            // 
            // CoverageSectionLabel
            // 
            CoverageSectionLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            CoverageSectionLabel.Font = new Font("Segoe UI", 15F, FontStyle.Bold);
            CoverageSectionLabel.ForeColor = Color.FromArgb(23, 45, 68);
            CoverageSectionLabel.Location = new Point(22, 16);
            CoverageSectionLabel.Name = "CoverageSectionLabel";
            CoverageSectionLabel.Size = new Size(522, 28);
            CoverageSectionLabel.TabIndex = 0;
            CoverageSectionLabel.Text = "Coverage && discounts";
            CoverageSectionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // CoverageInputCaptionLabel
            // 
            CoverageInputCaptionLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            CoverageInputCaptionLabel.Font = new Font("Segoe UI", 9F);
            CoverageInputCaptionLabel.ForeColor = Color.FromArgb(23, 45, 68);
            CoverageInputCaptionLabel.Location = new Point(22, 54);
            CoverageInputCaptionLabel.Name = "CoverageInputCaptionLabel";
            CoverageInputCaptionLabel.Size = new Size(522, 20);
            CoverageInputCaptionLabel.TabIndex = 1;
            CoverageInputCaptionLabel.Text = "Coverage amount ($)";
            CoverageInputCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // CoverageAmountTextBox
            // 
            CoverageAmountTextBox.AccessibleName = "Policy coverage amount in dollars";
            CoverageAmountTextBox.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            CoverageAmountTextBox.BorderStyle = BorderStyle.FixedSingle;
            CoverageAmountTextBox.Font = new Font("Segoe UI", 10F);
            CoverageAmountTextBox.Location = new Point(22, 78);
            CoverageAmountTextBox.Name = "CoverageAmountTextBox";
            CoverageAmountTextBox.PlaceholderText = "e.g., 100000";
            CoverageAmountTextBox.Size = new Size(522, 25);
            CoverageAmountTextBox.TabIndex = 0;
            // 
            // DiscountOptionsPanel
            // 
            DiscountOptionsPanel.AccessibleName = "Discount type";
            DiscountOptionsPanel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            DiscountOptionsPanel.Controls.Add(NoDiscountRadioButton);
            DiscountOptionsPanel.Controls.Add(PercentageDiscountRadioButton);
            DiscountOptionsPanel.Controls.Add(FlatDiscountRadioButton);
            DiscountOptionsPanel.Location = new Point(22, 116);
            DiscountOptionsPanel.Name = "DiscountOptionsPanel";
            DiscountOptionsPanel.Size = new Size(522, 30);
            DiscountOptionsPanel.TabIndex = 1;
            // 
            // NoDiscountRadioButton
            // 
            NoDiscountRadioButton.AutoSize = true;
            NoDiscountRadioButton.Checked = true;
            NoDiscountRadioButton.Font = new Font("Segoe UI", 9.5F);
            NoDiscountRadioButton.Location = new Point(0, 4);
            NoDiscountRadioButton.Name = "NoDiscountRadioButton";
            NoDiscountRadioButton.Size = new Size(97, 21);
            NoDiscountRadioButton.TabIndex = 0;
            NoDiscountRadioButton.TabStop = true;
            NoDiscountRadioButton.Text = "No discount";
            NoDiscountRadioButton.UseVisualStyleBackColor = true;
            // 
            // PercentageDiscountRadioButton
            // 
            PercentageDiscountRadioButton.AutoSize = true;
            PercentageDiscountRadioButton.Font = new Font("Segoe UI", 9.5F);
            PercentageDiscountRadioButton.Location = new Point(155, 4);
            PercentageDiscountRadioButton.Name = "PercentageDiscountRadioButton";
            PercentageDiscountRadioButton.Size = new Size(91, 21);
            PercentageDiscountRadioButton.TabIndex = 1;
            PercentageDiscountRadioButton.Text = "Percentage";
            PercentageDiscountRadioButton.UseVisualStyleBackColor = true;
            // 
            // FlatDiscountRadioButton
            // 
            FlatDiscountRadioButton.AutoSize = true;
            FlatDiscountRadioButton.Font = new Font("Segoe UI", 9.5F);
            FlatDiscountRadioButton.Location = new Point(330, 4);
            FlatDiscountRadioButton.Name = "FlatDiscountRadioButton";
            FlatDiscountRadioButton.Size = new Size(94, 21);
            FlatDiscountRadioButton.TabIndex = 2;
            FlatDiscountRadioButton.Text = "Flat amount";
            FlatDiscountRadioButton.UseVisualStyleBackColor = true;
            // 
            // DiscountAmountsLayout
            // 
            DiscountAmountsLayout.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            DiscountAmountsLayout.ColumnCount = 2;
            DiscountAmountsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            DiscountAmountsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            DiscountAmountsLayout.Controls.Add(PercentageDiscountCaptionLabel, 0, 0);
            DiscountAmountsLayout.Controls.Add(PercentageDiscountTextBox, 0, 1);
            DiscountAmountsLayout.Controls.Add(FlatDiscountCaptionLabel, 1, 0);
            DiscountAmountsLayout.Controls.Add(FlatDiscountTextBox, 1, 1);
            DiscountAmountsLayout.Location = new Point(22, 163);
            DiscountAmountsLayout.Margin = new Padding(0);
            DiscountAmountsLayout.Name = "DiscountAmountsLayout";
            DiscountAmountsLayout.RowCount = 2;
            DiscountAmountsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 22F));
            DiscountAmountsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            DiscountAmountsLayout.Size = new Size(522, 56);
            DiscountAmountsLayout.TabIndex = 2;
            // 
            // PercentageDiscountCaptionLabel
            // 
            PercentageDiscountCaptionLabel.Dock = DockStyle.Fill;
            PercentageDiscountCaptionLabel.Font = new Font("Segoe UI", 9F);
            PercentageDiscountCaptionLabel.ForeColor = Color.FromArgb(23, 45, 68);
            PercentageDiscountCaptionLabel.Location = new Point(0, 0);
            PercentageDiscountCaptionLabel.Margin = new Padding(0);
            PercentageDiscountCaptionLabel.Name = "PercentageDiscountCaptionLabel";
            PercentageDiscountCaptionLabel.Size = new Size(261, 22);
            PercentageDiscountCaptionLabel.TabIndex = 0;
            PercentageDiscountCaptionLabel.Text = "Percentage discount (%)";
            PercentageDiscountCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // PercentageDiscountTextBox
            // 
            PercentageDiscountTextBox.AccessibleName = "Percentage discount";
            PercentageDiscountTextBox.BorderStyle = BorderStyle.FixedSingle;
            PercentageDiscountTextBox.DataBindings.Add(new Binding("Enabled", PercentageDiscountRadioButton, "Checked", true, DataSourceUpdateMode.Never));
            PercentageDiscountTextBox.Dock = DockStyle.Top;
            PercentageDiscountTextBox.Enabled = false;
            PercentageDiscountTextBox.Font = new Font("Segoe UI", 10F);
            PercentageDiscountTextBox.Location = new Point(0, 24);
            PercentageDiscountTextBox.Margin = new Padding(0, 2, 10, 0);
            PercentageDiscountTextBox.Name = "PercentageDiscountTextBox";
            PercentageDiscountTextBox.PlaceholderText = "e.g., 5";
            PercentageDiscountTextBox.Size = new Size(251, 25);
            PercentageDiscountTextBox.TabIndex = 0;
            // 
            // FlatDiscountCaptionLabel
            // 
            FlatDiscountCaptionLabel.Dock = DockStyle.Fill;
            FlatDiscountCaptionLabel.Font = new Font("Segoe UI", 9F);
            FlatDiscountCaptionLabel.ForeColor = Color.FromArgb(23, 45, 68);
            FlatDiscountCaptionLabel.Location = new Point(261, 0);
            FlatDiscountCaptionLabel.Margin = new Padding(0);
            FlatDiscountCaptionLabel.Name = "FlatDiscountCaptionLabel";
            FlatDiscountCaptionLabel.Size = new Size(261, 22);
            FlatDiscountCaptionLabel.TabIndex = 1;
            FlatDiscountCaptionLabel.Text = "Flat discount ($)";
            FlatDiscountCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // FlatDiscountTextBox
            // 
            FlatDiscountTextBox.AccessibleName = "Flat dollar discount";
            FlatDiscountTextBox.BorderStyle = BorderStyle.FixedSingle;
            FlatDiscountTextBox.DataBindings.Add(new Binding("Enabled", FlatDiscountRadioButton, "Checked", true, DataSourceUpdateMode.Never));
            FlatDiscountTextBox.Dock = DockStyle.Top;
            FlatDiscountTextBox.Enabled = false;
            FlatDiscountTextBox.Font = new Font("Segoe UI", 10F);
            FlatDiscountTextBox.Location = new Point(261, 24);
            FlatDiscountTextBox.Margin = new Padding(0, 2, 0, 0);
            FlatDiscountTextBox.Name = "FlatDiscountTextBox";
            FlatDiscountTextBox.PlaceholderText = "e.g., 100";
            FlatDiscountTextBox.Size = new Size(261, 25);
            FlatDiscountTextBox.TabIndex = 1;
            // 
            // DiscountHintLabel
            // 
            DiscountHintLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            DiscountHintLabel.Font = new Font("Segoe UI", 8.5F);
            DiscountHintLabel.ForeColor = Color.FromArgb(88, 106, 126);
            DiscountHintLabel.Location = new Point(22, 227);
            DiscountHintLabel.Name = "DiscountHintLabel";
            DiscountHintLabel.Size = new Size(522, 18);
            DiscountHintLabel.TabIndex = 3;
            DiscountHintLabel.Text = "Choose one discount type, or select No discount.";
            DiscountHintLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // ValidationPanel
            // 
            ValidationPanel.BackColor = Color.FromArgb(255, 242, 240);
            ValidationPanel.BorderStyle = BorderStyle.FixedSingle;
            ValidationPanel.Controls.Add(ValidationHeadingLabel);
            ValidationPanel.Controls.Add(ValidationMessageLabel);
            ValidationPanel.Dock = DockStyle.Fill;
            ValidationPanel.Location = new Point(0, 512);
            ValidationPanel.Margin = new Padding(0);
            ValidationPanel.Name = "ValidationPanel";
            ValidationPanel.Size = new Size(568, 84);
            ValidationPanel.TabIndex = 2;
            ValidationPanel.Visible = false;
            // 
            // ValidationHeadingLabel
            // 
            ValidationHeadingLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            ValidationHeadingLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            ValidationHeadingLabel.ForeColor = Color.FromArgb(157, 48, 37);
            ValidationHeadingLabel.Location = new Point(14, 9);
            ValidationHeadingLabel.Name = "ValidationHeadingLabel";
            ValidationHeadingLabel.Size = new Size(536, 20);
            ValidationHeadingLabel.TabIndex = 0;
            ValidationHeadingLabel.Text = "Please review the entered details.";
            ValidationHeadingLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // ValidationMessageLabel
            // 
            ValidationMessageLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            ValidationMessageLabel.Font = new Font("Segoe UI", 9F);
            ValidationMessageLabel.ForeColor = Color.FromArgb(157, 48, 37);
            ValidationMessageLabel.Location = new Point(14, 33);
            ValidationMessageLabel.Name = "ValidationMessageLabel";
            ValidationMessageLabel.Size = new Size(536, 40);
            ValidationMessageLabel.TabIndex = 1;
            // 
            // QuotePanel
            // 
            QuotePanel.BackColor = Color.White;
            QuotePanel.BorderStyle = BorderStyle.FixedSingle;
            QuotePanel.Controls.Add(QuoteSectionLabel);
            QuotePanel.Controls.Add(PreparedForCaptionLabel);
            QuotePanel.Controls.Add(CustomerNameLabel);
            QuotePanel.Controls.Add(QuotedCoverageLayout);
            QuotePanel.Controls.Add(RiskLayout);
            QuotePanel.Controls.Add(QuoteAmountsLayout);
            QuotePanel.Controls.Add(TotalPanel);
            QuotePanel.Controls.Add(QuoteStatusLabel);
            QuotePanel.Dock = DockStyle.Fill;
            QuotePanel.Location = new Point(588, 0);
            QuotePanel.Margin = new Padding(0);
            QuotePanel.Name = "QuotePanel";
            QuotePanel.Size = new Size(484, 596);
            QuotePanel.TabIndex = 1;
            // 
            // QuoteSectionLabel
            // 
            QuoteSectionLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            QuoteSectionLabel.Font = new Font("Segoe UI", 15F, FontStyle.Bold);
            QuoteSectionLabel.ForeColor = Color.FromArgb(23, 45, 68);
            QuoteSectionLabel.Location = new Point(22, 16);
            QuoteSectionLabel.Name = "QuoteSectionLabel";
            QuoteSectionLabel.Size = new Size(436, 28);
            QuoteSectionLabel.TabIndex = 0;
            QuoteSectionLabel.Text = "Policy quotation";
            QuoteSectionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // PreparedForCaptionLabel
            // 
            PreparedForCaptionLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            PreparedForCaptionLabel.Font = new Font("Segoe UI", 8.5F);
            PreparedForCaptionLabel.ForeColor = Color.FromArgb(88, 106, 126);
            PreparedForCaptionLabel.Location = new Point(22, 56);
            PreparedForCaptionLabel.Name = "PreparedForCaptionLabel";
            PreparedForCaptionLabel.Size = new Size(436, 18);
            PreparedForCaptionLabel.TabIndex = 1;
            PreparedForCaptionLabel.Text = "PREPARED FOR";
            PreparedForCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // CustomerNameLabel
            // 
            CustomerNameLabel.AccessibleName = "Quoted customer name";
            CustomerNameLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            CustomerNameLabel.Font = new Font("Segoe UI", 12.5F, FontStyle.Bold);
            CustomerNameLabel.ForeColor = Color.FromArgb(23, 45, 68);
            CustomerNameLabel.Location = new Point(22, 78);
            CustomerNameLabel.Name = "CustomerNameLabel";
            CustomerNameLabel.Size = new Size(436, 38);
            CustomerNameLabel.TabIndex = 2;
            CustomerNameLabel.Text = "—";
            CustomerNameLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // QuotedCoverageLayout
            // 
            QuotedCoverageLayout.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            QuotedCoverageLayout.ColumnCount = 2;
            QuotedCoverageLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 45F));
            QuotedCoverageLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 55F));
            QuotedCoverageLayout.Controls.Add(QuotedCoverageCaptionLabel, 0, 0);
            QuotedCoverageLayout.Controls.Add(CoverageAmountLabel, 1, 0);
            QuotedCoverageLayout.Location = new Point(22, 124);
            QuotedCoverageLayout.Margin = new Padding(0);
            QuotedCoverageLayout.Name = "QuotedCoverageLayout";
            QuotedCoverageLayout.RowCount = 1;
            QuotedCoverageLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            QuotedCoverageLayout.Size = new Size(436, 28);
            QuotedCoverageLayout.TabIndex = 3;
            // 
            // QuotedCoverageCaptionLabel
            // 
            QuotedCoverageCaptionLabel.Dock = DockStyle.Fill;
            QuotedCoverageCaptionLabel.Font = new Font("Segoe UI", 9F);
            QuotedCoverageCaptionLabel.ForeColor = Color.FromArgb(88, 106, 126);
            QuotedCoverageCaptionLabel.Location = new Point(0, 0);
            QuotedCoverageCaptionLabel.Margin = new Padding(0);
            QuotedCoverageCaptionLabel.Name = "QuotedCoverageCaptionLabel";
            QuotedCoverageCaptionLabel.Size = new Size(196, 28);
            QuotedCoverageCaptionLabel.TabIndex = 0;
            QuotedCoverageCaptionLabel.Text = "Coverage amount";
            QuotedCoverageCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // CoverageAmountLabel
            // 
            CoverageAmountLabel.Dock = DockStyle.Fill;
            CoverageAmountLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            CoverageAmountLabel.ForeColor = Color.FromArgb(23, 45, 68);
            CoverageAmountLabel.Location = new Point(196, 0);
            CoverageAmountLabel.Margin = new Padding(0);
            CoverageAmountLabel.Name = "CoverageAmountLabel";
            CoverageAmountLabel.Size = new Size(240, 28);
            CoverageAmountLabel.TabIndex = 1;
            CoverageAmountLabel.Text = "—";
            CoverageAmountLabel.TextAlign = ContentAlignment.MiddleRight;
            // 
            // RiskLayout
            // 
            RiskLayout.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            RiskLayout.BackColor = Color.FromArgb(241, 245, 249);
            RiskLayout.ColumnCount = 2;
            RiskLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            RiskLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            RiskLayout.Controls.Add(RiskFactorCaptionLabel, 0, 0);
            RiskLayout.Controls.Add(RiskCategoryCaptionLabel, 1, 0);
            RiskLayout.Controls.Add(RiskFactorLabel, 0, 1);
            RiskLayout.Controls.Add(RiskCategoryLabel, 1, 1);
            RiskLayout.Location = new Point(22, 164);
            RiskLayout.Margin = new Padding(0);
            RiskLayout.Name = "RiskLayout";
            RiskLayout.Padding = new Padding(14, 10, 14, 8);
            RiskLayout.RowCount = 2;
            RiskLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 20F));
            RiskLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            RiskLayout.Size = new Size(436, 84);
            RiskLayout.TabIndex = 4;
            // 
            // RiskFactorCaptionLabel
            // 
            RiskFactorCaptionLabel.Dock = DockStyle.Fill;
            RiskFactorCaptionLabel.Font = new Font("Segoe UI", 9F);
            RiskFactorCaptionLabel.ForeColor = Color.FromArgb(88, 106, 126);
            RiskFactorCaptionLabel.Location = new Point(14, 10);
            RiskFactorCaptionLabel.Margin = new Padding(0);
            RiskFactorCaptionLabel.Name = "RiskFactorCaptionLabel";
            RiskFactorCaptionLabel.Size = new Size(204, 20);
            RiskFactorCaptionLabel.TabIndex = 0;
            RiskFactorCaptionLabel.Text = "Risk factor";
            RiskFactorCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // RiskCategoryCaptionLabel
            // 
            RiskCategoryCaptionLabel.Dock = DockStyle.Fill;
            RiskCategoryCaptionLabel.Font = new Font("Segoe UI", 9F);
            RiskCategoryCaptionLabel.ForeColor = Color.FromArgb(88, 106, 126);
            RiskCategoryCaptionLabel.Location = new Point(218, 10);
            RiskCategoryCaptionLabel.Margin = new Padding(0);
            RiskCategoryCaptionLabel.Name = "RiskCategoryCaptionLabel";
            RiskCategoryCaptionLabel.Size = new Size(204, 20);
            RiskCategoryCaptionLabel.TabIndex = 1;
            RiskCategoryCaptionLabel.Text = "Safe / unsafe";
            RiskCategoryCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // RiskFactorLabel
            // 
            RiskFactorLabel.AutoEllipsis = true;
            RiskFactorLabel.Dock = DockStyle.Fill;
            RiskFactorLabel.Font = new Font("Segoe UI", 19F, FontStyle.Bold);
            RiskFactorLabel.ForeColor = Color.FromArgb(23, 45, 68);
            RiskFactorLabel.Location = new Point(14, 30);
            RiskFactorLabel.Margin = new Padding(0);
            RiskFactorLabel.Name = "RiskFactorLabel";
            RiskFactorLabel.Size = new Size(204, 46);
            RiskFactorLabel.TabIndex = 2;
            RiskFactorLabel.Text = "—";
            RiskFactorLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // RiskCategoryLabel
            // 
            RiskCategoryLabel.Dock = DockStyle.Fill;
            RiskCategoryLabel.Font = new Font("Segoe UI", 19F, FontStyle.Bold);
            RiskCategoryLabel.ForeColor = Color.FromArgb(23, 45, 68);
            RiskCategoryLabel.Location = new Point(218, 30);
            RiskCategoryLabel.Margin = new Padding(0);
            RiskCategoryLabel.Name = "RiskCategoryLabel";
            RiskCategoryLabel.Size = new Size(204, 46);
            RiskCategoryLabel.TabIndex = 3;
            RiskCategoryLabel.Text = "—";
            RiskCategoryLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // QuoteAmountsLayout
            // 
            QuoteAmountsLayout.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            QuoteAmountsLayout.ColumnCount = 2;
            QuoteAmountsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 60F));
            QuoteAmountsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 40F));
            QuoteAmountsLayout.Controls.Add(CostPerThousandCaptionLabel, 0, 0);
            QuoteAmountsLayout.Controls.Add(CostPerThousandLabel, 1, 0);
            QuoteAmountsLayout.Controls.Add(AnnualPremiumCaptionLabel, 0, 1);
            QuoteAmountsLayout.Controls.Add(AnnualPremiumLabel, 1, 1);
            QuoteAmountsLayout.Controls.Add(DiscountAmountCaptionLabel, 0, 2);
            QuoteAmountsLayout.Controls.Add(DiscountAmountLabel, 1, 2);
            QuoteAmountsLayout.Controls.Add(SubtotalCaptionLabel, 0, 3);
            QuoteAmountsLayout.Controls.Add(SubtotalLabel, 1, 3);
            QuoteAmountsLayout.Controls.Add(SalesTaxCaptionLabel, 0, 4);
            QuoteAmountsLayout.Controls.Add(SalesTaxLabel, 1, 4);
            QuoteAmountsLayout.Location = new Point(22, 264);
            QuoteAmountsLayout.Margin = new Padding(0);
            QuoteAmountsLayout.Name = "QuoteAmountsLayout";
            QuoteAmountsLayout.RowCount = 5;
            QuoteAmountsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            QuoteAmountsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            QuoteAmountsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            QuoteAmountsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            QuoteAmountsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            QuoteAmountsLayout.Size = new Size(436, 156);
            QuoteAmountsLayout.TabIndex = 5;
            // 
            // CostPerThousandCaptionLabel
            // 
            CostPerThousandCaptionLabel.Dock = DockStyle.Fill;
            CostPerThousandCaptionLabel.Font = new Font("Segoe UI", 9F);
            CostPerThousandCaptionLabel.ForeColor = Color.FromArgb(88, 106, 126);
            CostPerThousandCaptionLabel.Location = new Point(0, 0);
            CostPerThousandCaptionLabel.Margin = new Padding(0);
            CostPerThousandCaptionLabel.Name = "CostPerThousandCaptionLabel";
            CostPerThousandCaptionLabel.Size = new Size(261, 31);
            CostPerThousandCaptionLabel.TabIndex = 0;
            CostPerThousandCaptionLabel.Text = "Cost per $1,000";
            CostPerThousandCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // CostPerThousandLabel
            // 
            CostPerThousandLabel.Dock = DockStyle.Fill;
            CostPerThousandLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            CostPerThousandLabel.ForeColor = Color.FromArgb(23, 45, 68);
            CostPerThousandLabel.Location = new Point(261, 0);
            CostPerThousandLabel.Margin = new Padding(0);
            CostPerThousandLabel.Name = "CostPerThousandLabel";
            CostPerThousandLabel.Size = new Size(175, 31);
            CostPerThousandLabel.TabIndex = 1;
            CostPerThousandLabel.Text = "—";
            CostPerThousandLabel.TextAlign = ContentAlignment.MiddleRight;
            // 
            // AnnualPremiumCaptionLabel
            // 
            AnnualPremiumCaptionLabel.Dock = DockStyle.Fill;
            AnnualPremiumCaptionLabel.Font = new Font("Segoe UI", 9F);
            AnnualPremiumCaptionLabel.ForeColor = Color.FromArgb(88, 106, 126);
            AnnualPremiumCaptionLabel.Location = new Point(0, 31);
            AnnualPremiumCaptionLabel.Margin = new Padding(0);
            AnnualPremiumCaptionLabel.Name = "AnnualPremiumCaptionLabel";
            AnnualPremiumCaptionLabel.Size = new Size(261, 31);
            AnnualPremiumCaptionLabel.TabIndex = 2;
            AnnualPremiumCaptionLabel.Text = "Annual premium";
            AnnualPremiumCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // AnnualPremiumLabel
            // 
            AnnualPremiumLabel.Dock = DockStyle.Fill;
            AnnualPremiumLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            AnnualPremiumLabel.ForeColor = Color.FromArgb(23, 45, 68);
            AnnualPremiumLabel.Location = new Point(261, 31);
            AnnualPremiumLabel.Margin = new Padding(0);
            AnnualPremiumLabel.Name = "AnnualPremiumLabel";
            AnnualPremiumLabel.Size = new Size(175, 31);
            AnnualPremiumLabel.TabIndex = 3;
            AnnualPremiumLabel.Text = "—";
            AnnualPremiumLabel.TextAlign = ContentAlignment.MiddleRight;
            // 
            // DiscountAmountCaptionLabel
            // 
            DiscountAmountCaptionLabel.Dock = DockStyle.Fill;
            DiscountAmountCaptionLabel.Font = new Font("Segoe UI", 9F);
            DiscountAmountCaptionLabel.ForeColor = Color.FromArgb(88, 106, 126);
            DiscountAmountCaptionLabel.Location = new Point(0, 62);
            DiscountAmountCaptionLabel.Margin = new Padding(0);
            DiscountAmountCaptionLabel.Name = "DiscountAmountCaptionLabel";
            DiscountAmountCaptionLabel.Size = new Size(261, 31);
            DiscountAmountCaptionLabel.TabIndex = 4;
            DiscountAmountCaptionLabel.Text = "Discount";
            DiscountAmountCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // DiscountAmountLabel
            // 
            DiscountAmountLabel.Dock = DockStyle.Fill;
            DiscountAmountLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            DiscountAmountLabel.ForeColor = Color.FromArgb(23, 45, 68);
            DiscountAmountLabel.Location = new Point(261, 62);
            DiscountAmountLabel.Margin = new Padding(0);
            DiscountAmountLabel.Name = "DiscountAmountLabel";
            DiscountAmountLabel.Size = new Size(175, 31);
            DiscountAmountLabel.TabIndex = 5;
            DiscountAmountLabel.Text = "—";
            DiscountAmountLabel.TextAlign = ContentAlignment.MiddleRight;
            // 
            // SubtotalCaptionLabel
            // 
            SubtotalCaptionLabel.Dock = DockStyle.Fill;
            SubtotalCaptionLabel.Font = new Font("Segoe UI", 9F);
            SubtotalCaptionLabel.ForeColor = Color.FromArgb(88, 106, 126);
            SubtotalCaptionLabel.Location = new Point(0, 93);
            SubtotalCaptionLabel.Margin = new Padding(0);
            SubtotalCaptionLabel.Name = "SubtotalCaptionLabel";
            SubtotalCaptionLabel.Size = new Size(261, 31);
            SubtotalCaptionLabel.TabIndex = 6;
            SubtotalCaptionLabel.Text = "Premium after discount";
            SubtotalCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // SubtotalLabel
            // 
            SubtotalLabel.Dock = DockStyle.Fill;
            SubtotalLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            SubtotalLabel.ForeColor = Color.FromArgb(23, 45, 68);
            SubtotalLabel.Location = new Point(261, 93);
            SubtotalLabel.Margin = new Padding(0);
            SubtotalLabel.Name = "SubtotalLabel";
            SubtotalLabel.Size = new Size(175, 31);
            SubtotalLabel.TabIndex = 7;
            SubtotalLabel.Text = "—";
            SubtotalLabel.TextAlign = ContentAlignment.MiddleRight;
            // 
            // SalesTaxCaptionLabel
            // 
            SalesTaxCaptionLabel.Dock = DockStyle.Fill;
            SalesTaxCaptionLabel.Font = new Font("Segoe UI", 9F);
            SalesTaxCaptionLabel.ForeColor = Color.FromArgb(88, 106, 126);
            SalesTaxCaptionLabel.Location = new Point(0, 124);
            SalesTaxCaptionLabel.Margin = new Padding(0);
            SalesTaxCaptionLabel.Name = "SalesTaxCaptionLabel";
            SalesTaxCaptionLabel.Size = new Size(261, 32);
            SalesTaxCaptionLabel.TabIndex = 8;
            SalesTaxCaptionLabel.Text = "Michigan sales tax";
            SalesTaxCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // SalesTaxLabel
            // 
            SalesTaxLabel.Dock = DockStyle.Fill;
            SalesTaxLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            SalesTaxLabel.ForeColor = Color.FromArgb(23, 45, 68);
            SalesTaxLabel.Location = new Point(261, 124);
            SalesTaxLabel.Margin = new Padding(0);
            SalesTaxLabel.Name = "SalesTaxLabel";
            SalesTaxLabel.Size = new Size(175, 32);
            SalesTaxLabel.TabIndex = 9;
            SalesTaxLabel.Text = "—";
            SalesTaxLabel.TextAlign = ContentAlignment.MiddleRight;
            // 
            // TotalPanel
            // 
            TotalPanel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            TotalPanel.BackColor = Color.FromArgb(23, 45, 68);
            TotalPanel.Controls.Add(TotalCaptionLabel);
            TotalPanel.Controls.Add(TotalAnnualPremiumLabel);
            TotalPanel.Controls.Add(TotalHintLabel);
            TotalPanel.Location = new Point(22, 438);
            TotalPanel.Name = "TotalPanel";
            TotalPanel.Size = new Size(436, 104);
            TotalPanel.TabIndex = 6;
            // 
            // TotalCaptionLabel
            // 
            TotalCaptionLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            TotalCaptionLabel.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            TotalCaptionLabel.ForeColor = Color.FromArgb(214, 228, 240);
            TotalCaptionLabel.Location = new Point(16, 10);
            TotalCaptionLabel.Name = "TotalCaptionLabel";
            TotalCaptionLabel.Size = new Size(404, 20);
            TotalCaptionLabel.TabIndex = 0;
            TotalCaptionLabel.Text = "TOTAL ANNUAL PREMIUM";
            TotalCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // TotalAnnualPremiumLabel
            // 
            TotalAnnualPremiumLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            TotalAnnualPremiumLabel.AutoEllipsis = true;
            TotalAnnualPremiumLabel.Font = new Font("Segoe UI", 23F, FontStyle.Bold);
            TotalAnnualPremiumLabel.ForeColor = Color.White;
            TotalAnnualPremiumLabel.Location = new Point(16, 34);
            TotalAnnualPremiumLabel.Name = "TotalAnnualPremiumLabel";
            TotalAnnualPremiumLabel.Size = new Size(404, 40);
            TotalAnnualPremiumLabel.TabIndex = 1;
            TotalAnnualPremiumLabel.Text = "—";
            TotalAnnualPremiumLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // TotalHintLabel
            // 
            TotalHintLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            TotalHintLabel.Font = new Font("Segoe UI", 8.5F);
            TotalHintLabel.ForeColor = Color.FromArgb(214, 228, 240);
            TotalHintLabel.Location = new Point(16, 80);
            TotalHintLabel.Name = "TotalHintLabel";
            TotalHintLabel.Size = new Size(404, 16);
            TotalHintLabel.TabIndex = 2;
            TotalHintLabel.Text = "Including discount and sales tax";
            TotalHintLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // QuoteStatusLabel
            // 
            QuoteStatusLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            QuoteStatusLabel.Font = new Font("Segoe UI", 9F);
            QuoteStatusLabel.ForeColor = Color.FromArgb(88, 106, 126);
            QuoteStatusLabel.Location = new Point(22, 561);
            QuoteStatusLabel.Name = "QuoteStatusLabel";
            QuoteStatusLabel.Size = new Size(436, 20);
            QuoteStatusLabel.TabIndex = 7;
            QuoteStatusLabel.Text = "No quote generated.";
            QuoteStatusLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // FooterPanel
            // 
            FooterPanel.BackColor = Color.White;
            FooterPanel.Controls.Add(FooterDivider);
            FooterPanel.Controls.Add(FooterHintLabel);
            FooterPanel.Controls.Add(ClearButton);
            FooterPanel.Controls.Add(GenerateQuoteButton);
            FooterPanel.Dock = DockStyle.Fill;
            FooterPanel.Location = new Point(0, 726);
            FooterPanel.Margin = new Padding(0);
            FooterPanel.Name = "FooterPanel";
            FooterPanel.Size = new Size(1120, 74);
            FooterPanel.TabIndex = 2;
            // 
            // FooterDivider
            // 
            FooterDivider.BackColor = Color.FromArgb(222, 229, 237);
            FooterDivider.Dock = DockStyle.Top;
            FooterDivider.Location = new Point(0, 0);
            FooterDivider.Name = "FooterDivider";
            FooterDivider.Size = new Size(1120, 1);
            FooterDivider.TabIndex = 0;
            // 
            // FooterHintLabel
            // 
            FooterHintLabel.Font = new Font("Segoe UI", 9F);
            FooterHintLabel.ForeColor = Color.FromArgb(88, 106, 126);
            FooterHintLabel.Location = new Point(24, 27);
            FooterHintLabel.Name = "FooterHintLabel";
            FooterHintLabel.Size = new Size(520, 20);
            FooterHintLabel.TabIndex = 1;
            FooterHintLabel.Text = "Review customer details before generating a quote.";
            FooterHintLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // ClearButton
            // 
            ClearButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            ClearButton.BackColor = Color.White;
            ClearButton.FlatAppearance.BorderColor = Color.FromArgb(186, 199, 213);
            ClearButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(243, 245, 248);
            ClearButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(241, 245, 249);
            ClearButton.FlatStyle = FlatStyle.Flat;
            ClearButton.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            ClearButton.ForeColor = Color.FromArgb(23, 45, 68);
            ClearButton.Location = new Point(828, 16);
            ClearButton.Name = "ClearButton";
            ClearButton.Size = new Size(90, 42);
            ClearButton.TabIndex = 1;
            ClearButton.Text = "&Clear";
            ClearButton.UseVisualStyleBackColor = false;
            ClearButton.Click += ClearButton_Click;
            // 
            // GenerateQuoteButton
            // 
            GenerateQuoteButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            GenerateQuoteButton.BackColor = Color.FromArgb(0, 122, 128);
            GenerateQuoteButton.FlatAppearance.BorderColor = Color.FromArgb(186, 199, 213);
            GenerateQuoteButton.FlatAppearance.BorderSize = 0;
            GenerateQuoteButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(0, 82, 88);
            GenerateQuoteButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(0, 102, 108);
            GenerateQuoteButton.FlatStyle = FlatStyle.Flat;
            GenerateQuoteButton.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            GenerateQuoteButton.ForeColor = Color.White;
            GenerateQuoteButton.Location = new Point(928, 16);
            GenerateQuoteButton.Name = "GenerateQuoteButton";
            GenerateQuoteButton.Size = new Size(168, 42);
            GenerateQuoteButton.TabIndex = 0;
            GenerateQuoteButton.Text = "&Generate quote";
            GenerateQuoteButton.UseVisualStyleBackColor = false;
            GenerateQuoteButton.Click += GenerateQuoteButton_Click;
            // 
            // InputErrorProvider
            // 
            InputErrorProvider.BlinkStyle = ErrorBlinkStyle.NeverBlink;
            InputErrorProvider.ContainerControl = this;
            // 
            // MainForm
            // 
            AcceptButton = GenerateQuoteButton;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(243, 245, 248);
            ClientSize = new Size(1120, 800);
            Controls.Add(RootLayout);
            Font = new Font("Segoe UI", 9F);
            ForeColor = Color.FromArgb(23, 45, 68);
            MinimumSize = new Size(1060, 740);
            Name = "MainForm";
            ShowIcon = false;
            StartPosition = FormStartPosition.CenterScreen;
            Text = "ChargEm — Life Insurance Quotation";
            RootLayout.ResumeLayout(false);
            HeaderPanel.ResumeLayout(false);
            BodyPanel.ResumeLayout(false);
            ContentLayout.ResumeLayout(false);
            InputLayout.ResumeLayout(false);
            CustomerPanel.ResumeLayout(false);
            NameLayout.ResumeLayout(false);
            NameLayout.PerformLayout();
            MeasurementsLayout.ResumeLayout(false);
            MeasurementsLayout.PerformLayout();
            CoveragePanel.ResumeLayout(false);
            CoveragePanel.PerformLayout();
            DiscountOptionsPanel.ResumeLayout(false);
            DiscountOptionsPanel.PerformLayout();
            DiscountAmountsLayout.ResumeLayout(false);
            DiscountAmountsLayout.PerformLayout();
            ValidationPanel.ResumeLayout(false);
            QuotePanel.ResumeLayout(false);
            QuotedCoverageLayout.ResumeLayout(false);
            RiskLayout.ResumeLayout(false);
            QuoteAmountsLayout.ResumeLayout(false);
            TotalPanel.ResumeLayout(false);
            FooterPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)InputErrorProvider).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private TableLayoutPanel RootLayout;
        private Panel HeaderPanel;
        private Label CompanyNameLabel;
        private Label CompanySubtitleLabel;
        private Label PageTitleLabel;
        private Panel BodyPanel;
        private TableLayoutPanel ContentLayout;
        private TableLayoutPanel InputLayout;
        private Panel CustomerPanel;
        private Label CustomerSectionLabel;
        private Label CustomerHintLabel;
        private TableLayoutPanel NameLayout;
        private Label FirstNameCaptionLabel;
        private TextBox FirstNameTextBox;
        private Label MiddleInitialCaptionLabel;
        private TextBox MiddleInitialTextBox;
        private Label LastNameCaptionLabel;
        private TextBox LastNameTextBox;
        private TableLayoutPanel MeasurementsLayout;
        private Label AgeCaptionLabel;
        private TextBox AgeTextBox;
        private Label HeightCaptionLabel;
        private TextBox HeightTextBox;
        private Label WeightCaptionLabel;
        private TextBox WeightTextBox;
        private Panel CoveragePanel;
        private Label CoverageSectionLabel;
        private Label CoverageInputCaptionLabel;
        private TextBox CoverageAmountTextBox;
        private Panel DiscountOptionsPanel;
        private RadioButton NoDiscountRadioButton;
        private RadioButton PercentageDiscountRadioButton;
        private RadioButton FlatDiscountRadioButton;
        private TableLayoutPanel DiscountAmountsLayout;
        private Label PercentageDiscountCaptionLabel;
        private TextBox PercentageDiscountTextBox;
        private Label FlatDiscountCaptionLabel;
        private TextBox FlatDiscountTextBox;
        private Label DiscountHintLabel;
        private Panel ValidationPanel;
        private Label ValidationHeadingLabel;
        private Label ValidationMessageLabel;
        private Panel QuotePanel;
        private Label QuoteSectionLabel;
        private Label PreparedForCaptionLabel;
        private Label CustomerNameLabel;
        private TableLayoutPanel QuotedCoverageLayout;
        private Label QuotedCoverageCaptionLabel;
        private Label CoverageAmountLabel;
        private TableLayoutPanel RiskLayout;
        private Label RiskFactorCaptionLabel;
        private Label RiskCategoryCaptionLabel;
        private Label RiskFactorLabel;
        private Label RiskCategoryLabel;
        private TableLayoutPanel QuoteAmountsLayout;
        private Label CostPerThousandCaptionLabel;
        private Label CostPerThousandLabel;
        private Label AnnualPremiumCaptionLabel;
        private Label AnnualPremiumLabel;
        private Label DiscountAmountCaptionLabel;
        private Label DiscountAmountLabel;
        private Label SubtotalCaptionLabel;
        private Label SubtotalLabel;
        private Label SalesTaxCaptionLabel;
        private Label SalesTaxLabel;
        private Panel TotalPanel;
        private Label TotalCaptionLabel;
        private Label TotalAnnualPremiumLabel;
        private Label TotalHintLabel;
        private Label QuoteStatusLabel;
        private Panel FooterPanel;
        private Panel FooterDivider;
        private Label FooterHintLabel;
        private Button ClearButton;
        private Button GenerateQuoteButton;
        private ErrorProvider InputErrorProvider;
    }
}
